# Site settings
title: YoGi Software Solutions
description: 'Crafting Excellence'
url: 'https://www.yogisoft.co'
baseurl: ''
profilepic: '/images/original-logo.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'YoGi Software Solutions'
  email: contact@yogisoft.co
  mastodon: 
  twitter_username:
#  facebook_username: joshgerdes
  github_username:  yogisoftco
  linkedin_username:  
  meetup_name: 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
